language: bash
addons:
  apt:
    sources:
    - debian-sid    # Grab ShellCheck from the Debian repo
    packages:
    - shellcheck
script:
  - bash -n create-kvm-manifest
  - bash -n create-lx-manifest
  - shellcheck -s bash create-kvm-manifest create-lx-manifest
